# Generated by Django 5.2.4 on 2025-07-31 23:16

from django.db.models import TextField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
