# Generated by Django 5.2.4 on 2025-08-12 18:54

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_parent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='media/text_files/', validators=[common.validators.validate_text_file_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='posts.post'),
        ),
    ]
