# Generated by Django 5.2.4 on 2025-08-24 18:02

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_text_file_alter_post_parent_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[common.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_files/', validators=[common.validators.validate_text_file_size]),
        ),
    ]
